[22/May/2017 09:16:36] "GET /WEB/sysadmin/alumnes/ HTTP/1.1" 302 0
[22/May/2017 09:16:36] "GET /WEB/login/?next=/WEB/sysadmin/alumnes/ HTTP/1.1" 200 1631
[22/May/2017 09:16:40] "POST /WEB/ HTTP/1.1" 302 0
[22/May/2017 09:16:40] "GET /WEB/ HTTP/1.1" 302 0
[22/May/2017 09:16:40] "GET /WEB/sysadmin/ HTTP/1.1" 200 3184
[22/May/2017 09:16:43] "GET /WEB/sysadmin/alumnes/ HTTP/1.1" 200 4797
[22/May/2017 09:16:54] "POST /API/alumnes/ HTTP/1.1" 400 79
Not Found: /API/alumnes/fred/dispositiu/
[22/May/2017 09:16:54] "POST /API/alumnes/fred/dispositiu/ HTTP/1.1" 404 46
[22/May/2017 09:17:36] "POST /API/alumnes/ HTTP/1.1" 403 3613
[22/May/2017 09:17:48] "GET /API/alumnes/ HTTP/1.1" 405 5388
[22/May/2017 09:17:52] "POST /API/alumnes/ HTTP/1.1" 201 5301
[22/May/2017 09:22:26] "GET /WEB/sysadmin/alumnes/ HTTP/1.1" 200 5194
[22/May/2017 09:22:29] "POST /API/alumnes/ HTTP/1.1" 400 79
Not Found: /API/alumnes/fred2/dispositiu/
[22/May/2017 09:22:29] "POST /API/alumnes/fred2/dispositiu/ HTTP/1.1" 404 46
[22/May/2017 09:26:02] "POST /API/alumnes/ HTTP/1.1" 400 79
Not Found: /API/alumnes/fredericu/dispositiu/
[22/May/2017 09:26:02] "POST /API/alumnes/fredericu/dispositiu/ HTTP/1.1" 404 46
Performing system checks...

System check identified no issues (0 silenced).
May 22, 2017 - 09:25:32
Django version 1.10.6, using settings 'attendancy.settings'
Starting development server at http://10.4.41.154:8000/
Quit the server with CONTROL-C.
{}
{'username': [u'This field is required.'], 'password': [u'This field is required.']}
{}
fredericu
[22/May/2017 09:27:37] "GET /API/alumnes/ HTTP/1.1" 405 5388
Internal Server Error: /API/alumnes/
Traceback (most recent call last):
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/decorators.py", line 52, in handler
    return func(*args, **kwargs)
  File "/home/alumne/Attendancy/API/views.py", line 37, in altaAlumne
    alumne.save()
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: UNIQUE constraint failed: API_alumne.dni
[22/May/2017 09:27:57] "POST /API/alumnes/ HTTP/1.1" 500 152941
[22/May/2017 09:27:58] "POST /API/alumnes/ HTTP/1.1" 400 5404
[22/May/2017 09:27:59] "GET /API/alumnes/ HTTP/1.1" 405 5388
Internal Server Error: /API/alumnes/
Traceback (most recent call last):
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/decorators.py", line 52, in handler
    return func(*args, **kwargs)
  File "/home/alumne/Attendancy/API/views.py", line 37, in altaAlumne
    alumne.save()
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: UNIQUE constraint failed: API_alumne.dni
[22/May/2017 09:28:07] "POST /API/alumnes/ HTTP/1.1" 500 152927
[22/May/2017 09:28:11] "GET /API/alumnes/ HTTP/1.1" 405 5388
[22/May/2017 09:28:17] "POST /API/alumnes/ HTTP/1.1" 400 5404
[22/May/2017 09:28:30] "POST /API/alumnes/ HTTP/1.1" 201 5301
[22/May/2017 09:29:23] "GET /WEB/sysadmin/alumnes/ HTTP/1.1" 200 5603
[22/May/2017 09:30:42] "GET /WEB/sysadmin/delete/?alumne=fred123235 HTTP/1.1" 302 0
[22/May/2017 09:30:42] "GET /WEB/sysadmin/alumnes/ HTTP/1.1" 200 5194
[22/May/2017 09:30:55] "GET /WEB/sysadmin/delete/?alumne=fred HTTP/1.1" 302 0
[22/May/2017 09:30:56] "GET /WEB/sysadmin/alumnes/ HTTP/1.1" 200 4797
[22/May/2017 09:31:18] "POST /API/alumnes/ HTTP/1.1" 400 79
Not Found: /API/alumnes/frederic/dispositiu/
[22/May/2017 09:31:18] "POST /API/alumnes/frederic/dispositiu/ HTTP/1.1" 404 46
[22/May/2017 09:36:01] "POST /API/alumnes/ HTTP/1.1" 400 79
Not Found: /API/alumnes/fredi/dispositiu/
[22/May/2017 09:36:01] "POST /API/alumnes/fredi/dispositiu/ HTTP/1.1" 404 46
[22/May/2017 09:43:04] "GET /WEB/sysadmin/alumnes/ HTTP/1.1" 200 4797
Not Found: /favicon.ico
[22/May/2017 09:43:05] "GET /favicon.ico HTTP/1.1" 404 2262
[22/May/2017 09:43:07] "GET /WEB/sysadmin/alumnes/ HTTP/1.1" 200 4797
[22/May/2017 09:43:13] "GET /WEB/sysadmin/assignatures/ HTTP/1.1" 200 4244
[22/May/2017 09:43:26] "GET /WEB/sysadmin/crearclasse HTTP/1.1" 301 0
[22/May/2017 09:43:26] "GET /WEB/sysadmin/crearclasse/ HTTP/1.1" 200 23444
[22/May/2017 09:43:34] "GET /API/classes?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 301 0
[22/May/2017 09:43:34] "GET /API/classes/?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 200 205
[22/May/2017 09:43:42] "GET /WEB/sysadmin/classesassignatura/?assignatura=PTI HTTP/1.1" 200 4018
Internal Server Error: /API/classes/47/assistencia/04:1B:BA:4A:1F:C3/
Traceback (most recent call last):
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/alumne/Attendancy/API/views.py", line 100, in post
    assistencia.save(True)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: UNIQUE constraint failed: API_assistencia.id
[22/May/2017 09:43:59] "POST /API/classes/47/assistencia/04:1B:BA:4A:1F:C3/ HTTP/1.1" 500 17957
[22/May/2017 09:44:18] "GET /WEB/logout/ HTTP/1.1" 302 0
[22/May/2017 09:44:18] "GET /WEB/ HTTP/1.1" 200 1588
[22/May/2017 09:44:25] "POST /WEB/ HTTP/1.1" 302 0
[22/May/2017 09:44:26] "GET /WEB/ HTTP/1.1" 302 0
[22/May/2017 09:44:26] "GET /WEB/profe/ HTTP/1.1" 200 3054
[22/May/2017 09:44:28] "GET /WEB/profe/calendar/ HTTP/1.1" 200 5503
[22/May/2017 09:44:32] "GET /WEB/profe/json/?from=1493589600000&to=1496268000000 HTTP/1.1" 200 6081
[22/May/2017 09:44:32] "GET /static/tmpls/month.html?_=1495442617527 HTTP/1.1" 200 935
[22/May/2017 09:44:32] "GET /static/tmpls/month-day.html?_=1495442617594 HTTP/1.1" 200 625
[22/May/2017 09:44:33] "GET /static/tmpls/events-list.html?_=1495442617739 HTTP/1.1" 200 490
[22/May/2017 09:44:34] "GET /WEB/profe/assistenciaclasse/?classe=47&data=2017-05-22%2008:00:00 HTTP/1.1" 200 4124
[22/May/2017 09:44:40] "GET /WEB/profe/assistenciaclasse/?classe=47&data=2017-05-22%2008:00:00 HTTP/1.1" 200 4124
Performing system checks...

System check identified no issues (0 silenced).
May 22, 2017 - 09:35:35
Django version 1.10.6, using settings 'attendancy.settings'
Starting development server at http://10.4.41.154:8000/
Quit the server with CONTROL-C.
Alta alumne
{}
{'username': [u'This field is required.'], 'password': [u'This field is required.']}
{}
fredi
B8:27:EB:B4:E2:05
post assistencia
19:21
Assistencia object
[22/May/2017 09:46:25] "GET /WEB/profe/assistenciaclasse/?classe=47&data=2017-05-22%2008:00:00 HTTP/1.1" 200 4502
[22/May/2017 09:49:26] "GET /WEB/profe/assistenciaclasse/?classe=47&data=2017-05-22%2008:00:00 HTTP/1.1" 200 4502
[22/May/2017 09:49:50] "GET /WEB/profe/assistenciaclasse/?classe=47&data=2017-05-22%2008:00:00 HTTP/1.1" 200 4502
[22/May/2017 09:50:57] "GET /WEB/profe/assistenciaclasse/?classe=47&data=2017-05-22%2008:00:00 HTTP/1.1" 200 4502
[22/May/2017 09:50:59] "GET /WEB/profe/assistenciaclasse/?classe=47&data=2017-05-22%2008:00:00 HTTP/1.1" 200 4502
[22/May/2017 09:51:00] "GET /WEB/profe/assistenciaclasse/?classe=47&data=2017-05-22%2008:00:00 HTTP/1.1" 200 4502
[22/May/2017 09:51:00] "GET /static/css/main.css HTTP/1.1" 304 0
[22/May/2017 09:51:00] "GET /static/js/moment.js HTTP/1.1" 304 0
[22/May/2017 09:51:00] "GET /static/js/bootstrap-datetimepicker.min.js HTTP/1.1" 304 0
[22/May/2017 09:51:00] "GET /static/css/bootstrap-datetimepicker.min.css HTTP/1.1" 304 0
[22/May/2017 09:51:14] "GET /API/alumnes/ HTTP/1.1" 405 5388
[22/May/2017 09:51:17] "GET /WEB/profe/assistenciaclasse/?classe=47&data=2017-05-22%2008:00:00 HTTP/1.1" 200 4502
[22/May/2017 09:51:29] "GET /WEB/profe/calendar/ HTTP/1.1" 200 5503
[22/May/2017 09:51:30] "GET /WEB/profe/json/?from=1493589600000&to=1496268000000 HTTP/1.1" 200 6081
[22/May/2017 09:51:30] "GET /static/tmpls/month.html?_=1495443034705 HTTP/1.1" 200 935
[22/May/2017 09:51:30] "GET /static/tmpls/month-day.html?_=1495443034753 HTTP/1.1" 200 625
[22/May/2017 09:51:30] "GET /static/tmpls/events-list.html?_=1495443034870 HTTP/1.1" 200 490
[22/May/2017 09:51:33] "GET /WEB/profe/json/?from=1490997600000&to=1493589600000 HTTP/1.1" 200 6081
[22/May/2017 09:51:34] "GET /WEB/profe/json/?from=1488322800000&to=1490997600000 HTTP/1.1" 200 5013
[22/May/2017 09:51:35] "GET /WEB/profe/json/?from=1485903600000&to=1488322800000 HTTP/1.1" 200 1809
[22/May/2017 09:51:46] "GET /WEB/profe/assistenciaclasse?classe=47&data=2017-02-13%2008:00:00 HTTP/1.1" 301 0
[22/May/2017 09:51:46] "GET /WEB/profe/assistenciaclasse/?classe=47&data=2017-02-13%2008:00:00 HTTP/1.1" 200 4572
[22/May/2017 09:52:01] "GET /WEB/profe/calendar HTTP/1.1" 301 0
[22/May/2017 09:52:01] "GET /WEB/profe/calendar/ HTTP/1.1" 200 5503
[22/May/2017 09:52:01] "GET /WEB/profe/json/?from=1493589600000&to=1496268000000 HTTP/1.1" 200 6081
[22/May/2017 09:52:01] "GET /static/tmpls/month.html?_=1495443066552 HTTP/1.1" 200 935
[22/May/2017 09:52:01] "GET /static/tmpls/month-day.html?_=1495443066593 HTTP/1.1" 200 625
[22/May/2017 09:52:02] "GET /static/tmpls/events-list.html?_=1495443066718 HTTP/1.1" 200 490
[22/May/2017 09:52:12] "GET /WEB/profe/assistenciaclasse/?classe=47&data=2017-05-22%2008:00:00 HTTP/1.1" 200 4502
[22/May/2017 09:52:47] "GET /WEB/ HTTP/1.1" 302 0
[22/May/2017 09:52:47] "GET /WEB/profe/ HTTP/1.1" 200 3054
Not Found: /favicon.ico
[22/May/2017 09:52:47] "GET /favicon.ico HTTP/1.1" 404 2262
[22/May/2017 09:52:49] "GET /WEB/profe/calendar/ HTTP/1.1" 200 5503
[22/May/2017 09:52:49] "GET /WEB/profe/json/?from=1493589600000&to=1496268000000 HTTP/1.1" 200 6081
[22/May/2017 09:52:49] "GET /static/tmpls/month.html?_=1495443114200 HTTP/1.1" 200 935
[22/May/2017 09:52:49] "GET /static/tmpls/month-day.html?_=1495443114213 HTTP/1.1" 200 625
[22/May/2017 09:52:49] "GET /static/tmpls/events-list.html?_=1495443114298 HTTP/1.1" 200 490
[22/May/2017 09:52:52] "GET /WEB/profe/assistenciaclasse?classe=47&data=2017-05-22%2008:00:00 HTTP/1.1" 301 0
[22/May/2017 09:52:52] "GET /WEB/profe/assistenciaclasse/?classe=47&data=2017-05-22%2008:00:00 HTTP/1.1" 200 4502
[22/May/2017 09:58:39] "GET /API/classes?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 301 0
[22/May/2017 09:58:39] "GET /API/classes/?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 200 205
[22/May/2017 09:59:23] "GET /API/classes?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 301 0
[22/May/2017 09:59:23] "GET /API/classes/?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 200 205
Internal Server Error: /API/classes/47/assistencia/04:1B:BA:4A:1F:C3/
Traceback (most recent call last):
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/alumne/Attendancy/API/views.py", line 100, in post
    assistencia.save(True)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: UNIQUE constraint failed: API_assistencia.id
[22/May/2017 10:00:11] "POST /API/classes/47/assistencia/04:1B:BA:4A:1F:C3/ HTTP/1.1" 500 17957
[22/May/2017 10:00:33] "GET /WEB/logout/ HTTP/1.1" 302 0
[22/May/2017 10:00:34] "GET /WEB/ HTTP/1.1" 200 1588
[22/May/2017 10:00:37] "POST /WEB/ HTTP/1.1" 302 0
[22/May/2017 10:00:37] "GET /WEB/ HTTP/1.1" 302 0
[22/May/2017 10:00:37] "GET /WEB/sysadmin/ HTTP/1.1" 200 3184
[22/May/2017 10:00:41] "GET /WEB/sysadmin/assignatures/ HTTP/1.1" 200 4244
[22/May/2017 10:00:53] "GET /WEB/sysadmin/delete/?assignatura=PTI HTTP/1.1" 302 0
[22/May/2017 10:00:53] "GET /WEB/sysadmin/assignatures/ HTTP/1.1" 200 3885
[22/May/2017 10:01:01] "GET /WEB/sysadmin/crearclasse/ HTTP/1.1" 200 23444
[22/May/2017 10:01:03] "GET /API/classes?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 301 0
Not Found: /API/classes/
[22/May/2017 10:01:03] "GET /API/classes/?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 404 46
[22/May/2017 10:01:34] "POST /WEB/sysadmin/crearclasse/ HTTP/1.1" 302 0
[22/May/2017 10:01:34] "GET /WEB/sysadmin/assignatures HTTP/1.1" 301 0
[22/May/2017 10:01:34] "GET /WEB/sysadmin/assignatures/ HTTP/1.1" 200 4244
[22/May/2017 10:01:37] "GET /WEB/sysadmin/classesassignatura/?assignatura=PTI HTTP/1.1" 200 4013
[22/May/2017 10:04:07] "GET /WEB/sysadmin/alumnes/ HTTP/1.1" 200 4797
[22/May/2017 10:04:11] "GET /WEB/logout/ HTTP/1.1" 302 0
[22/May/2017 10:04:11] "GET /WEB/ HTTP/1.1" 200 1588
[22/May/2017 10:04:14] "POST /WEB/ HTTP/1.1" 302 0
[22/May/2017 10:04:14] "GET /WEB/ HTTP/1.1" 302 0
[22/May/2017 10:04:14] "GET /WEB/profe/ HTTP/1.1" 200 3054
[22/May/2017 10:04:21] "GET /WEB/profe/assigsprofessor/ HTTP/1.1" 200 4063
[22/May/2017 10:04:22] "GET /WEB/profe/calendar/ HTTP/1.1" 200 5503
[22/May/2017 10:04:22] "GET /WEB/profe/json/?from=1493589600000&to=1496268000000 HTTP/1.1" 200 6257
[22/May/2017 10:04:22] "GET /static/tmpls/month.html?_=1495443807334 HTTP/1.1" 200 935
[22/May/2017 10:04:22] "GET /static/tmpls/month-day.html?_=1495443807350 HTTP/1.1" 200 625
[22/May/2017 10:04:22] "GET /static/tmpls/events-list.html?_=1495443807468 HTTP/1.1" 200 490
[22/May/2017 10:04:24] "GET /WEB/profe/assistenciaclasse?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 301 0
[22/May/2017 10:04:24] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 10:04:30] "GET /WEB/profe/calendar/ HTTP/1.1" 200 5503
[22/May/2017 10:04:30] "GET /WEB/profe/json/?from=1493589600000&to=1496268000000 HTTP/1.1" 200 6257
[22/May/2017 10:04:31] "GET /static/tmpls/month.html?_=1495443815660 HTTP/1.1" 200 935
[22/May/2017 10:04:31] "GET /static/tmpls/month-day.html?_=1495443815674 HTTP/1.1" 200 625
[22/May/2017 10:04:31] "GET /static/tmpls/events-list.html?_=1495443815757 HTTP/1.1" 200 490
[22/May/2017 10:04:32] "GET /WEB/profe/assigsprofessor/ HTTP/1.1" 200 4063
[22/May/2017 10:04:35] "GET /WEB/profe/classesassigprofessor/?assignatura=PTI HTTP/1.1" 200 3880
[22/May/2017 10:04:41] "GET /WEB/profe/alumnesprofessor/?assignatura=PTI HTTP/1.1" 200 3679
[22/May/2017 10:04:44] "GET /WEB/profe/historialAlumne?alumne=fredy&assignatura=PTI HTTP/1.1" 301 0
[22/May/2017 10:04:44] "GET /WEB/profe/historialAlumne/?alumne=fredy&assignatura=PTI HTTP/1.1" 200 9095
[22/May/2017 10:05:21] "GET /WEB/profe/calendar/ HTTP/1.1" 200 5503
[22/May/2017 10:05:21] "GET /WEB/profe/json/?from=1493589600000&to=1496268000000 HTTP/1.1" 200 6257
[22/May/2017 10:05:21] "GET /static/tmpls/month.html?_=1495443866071 HTTP/1.1" 200 935
[22/May/2017 10:05:21] "GET /static/tmpls/month-day.html?_=1495443866086 HTTP/1.1" 200 625
[22/May/2017 10:05:21] "GET /static/tmpls/events-list.html?_=1495443866174 HTTP/1.1" 200 490
[22/May/2017 10:05:24] "GET /WEB/profe/assistenciaclasse?classe=52&data=2017-05-24%2010:00:00 HTTP/1.1" 301 0
[22/May/2017 10:05:24] "GET /WEB/profe/assistenciaclasse/?classe=52&data=2017-05-24%2010:00:00 HTTP/1.1" 200 4124
[22/May/2017 10:05:32] "GET /static/tmpls/month.html?_=1495443876862 HTTP/1.1" 200 935
[22/May/2017 10:05:32] "GET /static/tmpls/month-day.html?_=1495443876956 HTTP/1.1" 200 625
[22/May/2017 10:05:32] "GET /static/tmpls/events-list.html?_=1495443877044 HTTP/1.1" 200 490
[22/May/2017 10:05:33] "GET /WEB/profe/assistenciaclasse?classe=50&data=2017-05-18%2008:00:00 HTTP/1.1" 301 0
[22/May/2017 10:05:33] "GET /WEB/profe/assistenciaclasse/?classe=50&data=2017-05-18%2008:00:00 HTTP/1.1" 200 4125
[22/May/2017 10:05:36] "GET /WEB/profe/assistenciaclasse?classe=52&data=2017-05-17%2010:00:00 HTTP/1.1" 301 0
[22/May/2017 10:05:36] "GET /WEB/profe/assistenciaclasse/?classe=52&data=2017-05-17%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 10:05:49] "GET /API/classes?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 301 0
[22/May/2017 10:05:49] "GET /API/classes/?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 200 163
Internal Server Error: /API/classes/51/assistencia/04:1B:BA:4A:1F:C3/
Traceback (most recent call last):
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/alumne/Attendancy/API/views.py", line 100, in post
    assistencia.save(True)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: UNIQUE constraint failed: API_assistencia.id
[22/May/2017 10:05:53] "POST /API/classes/51/assistencia/04:1B:BA:4A:1F:C3/ HTTP/1.1" 500 17957
[22/May/2017 10:06:11] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 10:07:57] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 10:09:23] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 10:09:25] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 10:09:26] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 10:09:27] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 10:09:28] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
Performing system checks...

System check identified no issues (0 silenced).
May 22, 2017 - 09:46:23
Django version 1.10.6, using settings 'attendancy.settings'
Starting development server at http://10.4.41.154:8000/
Quit the server with CONTROL-C.
subi1
2017-05-22
subi2
2017-05-22
fredy
2017-05-22
subi1
2017-05-22
subi2
2017-05-22
fredy
2017-05-22
subi1
2017-05-22
subi2
2017-05-22
fredy
2017-05-22
subi1
2017-05-22
subi2
2017-05-22
fredy
2017-05-22
subi1
2017-05-22
subi2
2017-05-22
fredy
2017-05-22
subi1
2017-05-22
subi2
2017-05-22
fredy
2017-05-22
subi1
2017-05-22
subi2
2017-05-22
fredy
2017-05-22
subi1
2017-02-13
subi2
2017-02-13
fredy
2017-02-13
subi1
2017-05-22
subi2
2017-05-22
fredy
2017-05-22
subi1
2017-05-22
subi2
2017-05-22
fredy
2017-05-22
B8:27:EB:B4:E2:05
B8:27:EB:B4:E2:05
post assistencia
9:59
Assistencia object
B8:27:EB:B4:E2:05
fredy
2017-05-22
fredy
2017-05-17
B8:27:EB:B4:E2:05
post assistencia
10:5
Assistencia object
fredy
2017-05-22
fredy
2017-05-22
fredy
2017-05-22
fredy
2017-05-22
fredy
2017-05-22
fredy
2017-05-22
fredy
2017-05-22
[22/May/2017 10:11:19] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 10:11:35] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 10:12:16] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4325
[22/May/2017 10:12:39] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 10:20:27] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 10:20:30] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 10:22:06] "GET /API/classes?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 301 0
[22/May/2017 10:22:06] "GET /API/classes/?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 200 163
Internal Server Error: /API/classes/51/assistencia/04:1B:BA:4A:1F:C3/
Traceback (most recent call last):
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/alumne/Attendancy/API/views.py", line 100, in post
    assistencia.save(True)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: UNIQUE constraint failed: API_assistencia.id
[22/May/2017 10:22:11] "POST /API/classes/51/assistencia/04:1B:BA:4A:1F:C3/ HTTP/1.1" 500 17957
Performing system checks...

System check identified no issues (0 silenced).
May 22, 2017 - 10:10:19
Django version 1.10.6, using settings 'attendancy.settings'
Starting development server at http://10.4.41.154:8000/
Quit the server with CONTROL-C.
fredy
2017-05-22
fredy
2017-05-22
fredy
2017-05-22
fredy
2017-05-22
fredy
2017-05-22
fredy
2017-05-22
B8:27:EB:B4:E2:05
post assistencia
10:0
Assistencia object
[22/May/2017 10:28:07] "GET /API/classes?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 301 0
[22/May/2017 10:28:07] "GET /API/classes/?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 200 163
[22/May/2017 10:28:11] "POST /API/classes/51/assistencia/04:1B:BA:4A:1F:C3/ HTTP/1.1" 201 0
[22/May/2017 10:28:23] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 10:31:20] "PUT /API/classes/51/assistencia/04:1B:BA:4A:1F:C3/ HTTP/1.1" 400 41
[22/May/2017 10:31:41] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
Performing system checks...

System check identified no issues (0 silenced).
May 22, 2017 - 10:26:03
Django version 1.10.6, using settings 'attendancy.settings'
Starting development server at http://10.4.41.154:8000/
Quit the server with CONTROL-C.
B8:27:EB:B4:E2:05
post assistencia
10:6
Assistencia object
fredy
2017-05-22
fredy
2017-05-22
[22/May/2017 10:37:51] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 10:38:06] "POST /API/classes/51/assistencia/04:1B:BA:4A:1F:C3/ HTTP/1.1" 201 0
[22/May/2017 10:38:24] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 10:38:26] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 10:38:27] "GET /static/js/moment.js HTTP/1.1" 304 0
[22/May/2017 10:38:27] "GET /static/css/main.css HTTP/1.1" 304 0
[22/May/2017 10:38:27] "GET /static/js/bootstrap-datetimepicker.min.js HTTP/1.1" 304 0
[22/May/2017 10:38:27] "GET /static/css/bootstrap-datetimepicker.min.css HTTP/1.1" 304 0
[22/May/2017 10:38:32] "GET /WEB/profe/assigsprofessor/ HTTP/1.1" 200 4063
[22/May/2017 10:38:36] "GET /WEB/profe/alumnesprofessor/?assignatura=PTI HTTP/1.1" 200 3679
Internal Server Error: /WEB/profe/historialAlumne/
Traceback (most recent call last):
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/alumne/Attendancy/WEB/views.py", line 438, in historial_alumne
    if assist.entrada >= event.start.time() and assist.sortida <= event.end.time():
TypeError: can't compare datetime.time to NoneType
[22/May/2017 10:38:37] "GET /WEB/profe/historialAlumne/?alumne=fredy&assignatura=PTI HTTP/1.1" 500 84693
[22/May/2017 10:38:57] "GET /WEB/profe/calendar/ HTTP/1.1" 200 5503
[22/May/2017 10:38:58] "GET /WEB/profe/json/?from=1493589600000&to=1496268000000 HTTP/1.1" 200 6257
[22/May/2017 10:38:58] "GET /static/tmpls/month.html?_=1495445882705 HTTP/1.1" 200 935
[22/May/2017 10:38:58] "GET /static/tmpls/month-day.html?_=1495445882722 HTTP/1.1" 200 625
[22/May/2017 10:38:58] "GET /static/tmpls/events-list.html?_=1495445882810 HTTP/1.1" 200 490
[22/May/2017 10:39:02] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 10:40:53] "PUT /API/classes/51/assistencia/04:1B:BA:4A:1F:C3/ HTTP/1.1" 204 0
Performing system checks...

System check identified no issues (0 silenced).
May 22, 2017 - 10:36:45
Django version 1.10.6, using settings 'attendancy.settings'
Starting development server at http://10.4.41.154:8000/
Quit the server with CONTROL-C.
fredy
2017-05-22
post assistencia
10:16
Assistencia object
fredy
2017-05-22
fredy
2017-05-22
fredy
2017-05-22
[22/May/2017 10:42:34] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4327
[22/May/2017 10:42:48] "GET /WEB/profe/ HTTP/1.1" 200 3054
[22/May/2017 10:42:49] "GET /WEB/profe/assigsprofessor/ HTTP/1.1" 200 4063
[22/May/2017 10:42:52] "GET /WEB/profe/alumnesprofessor/?assignatura=PTI HTTP/1.1" 200 3679
[22/May/2017 10:42:54] "GET /WEB/profe/historialAlumne/?alumne=fredy&assignatura=PTI HTTP/1.1" 200 9095
[22/May/2017 10:46:26] "GET /WEB/profe/alumnesprofessor/?assignatura=PTI HTTP/1.1" 200 3679
[22/May/2017 10:46:27] "GET /WEB/profe/alumnesprofessor/?assignatura=PTI HTTP/1.1" 200 3679
[22/May/2017 10:46:28] "GET /API/classes?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 301 0
[22/May/2017 10:46:28] "GET /API/classes/?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 200 163
[22/May/2017 10:46:29] "GET /WEB/profe/calendar/ HTTP/1.1" 200 5503
[22/May/2017 10:46:29] "GET /WEB/profe/json/?from=1493589600000&to=1496268000000 HTTP/1.1" 200 6257
[22/May/2017 10:46:29] "GET /static/tmpls/month.html?_=1495446334373 HTTP/1.1" 200 935
[22/May/2017 10:46:29] "GET /static/tmpls/month-day.html?_=1495446334390 HTTP/1.1" 200 625
[22/May/2017 10:46:29] "GET /static/tmpls/events-list.html?_=1495446334482 HTTP/1.1" 200 490
[22/May/2017 10:46:31] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4327
[22/May/2017 10:46:38] "GET /API/classes?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 301 0
[22/May/2017 10:46:38] "GET /API/classes/?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 200 163
[22/May/2017 10:46:45] "GET /API/classes?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 301 0
[22/May/2017 10:46:45] "GET /API/classes/?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 200 163
[22/May/2017 10:47:09] "GET /API/classes?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 301 0
[22/May/2017 10:47:09] "GET /API/classes/?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 200 163
[22/May/2017 10:47:19] "GET /API/classes?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 301 0
[22/May/2017 10:47:19] "GET /API/classes/?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 200 163
[22/May/2017 10:48:13] "GET /API/classes?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 301 0
[22/May/2017 10:48:13] "GET /API/classes/?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 200 163
Performing system checks...

System check identified no issues (0 silenced).
May 22, 2017 - 10:42:30
Django version 1.10.6, using settings 'attendancy.settings'
Starting development server at http://10.4.41.154:8000/
Quit the server with CONTROL-C.
fredy
2017-05-22
B8:27:EB:B4:E2:05
fredy
2017-05-22
B8:27:EB:B4:E2:05
B8:27:EB:B4:E2:05
B8:27:EB:B4:E2:05
B8:27:EB:B4:E2:05
B8:27:EB:B4:E2:05
[22/May/2017 10:49:37] "GET /API/classes?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 301 0
[22/May/2017 10:49:37] "GET /API/classes/?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 200 163
[22/May/2017 10:50:13] "GET /API/classes?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 301 0
[22/May/2017 10:50:13] "GET /API/classes/?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 200 163
Performing system checks...

System check identified no issues (0 silenced).
May 22, 2017 - 10:48:15
Django version 1.10.6, using settings 'attendancy.settings'
Starting development server at http://10.4.41.154:8000/
Quit the server with CONTROL-C.
B8:27:EB:B4:E2:05
B8:27:EB:B4:E2:05
[22/May/2017 10:51:24] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 10:51:32] "POST /API/classes/51/assistencia/04:1B:BA:4A:1F:C3/ HTTP/1.1" 201 0
[22/May/2017 10:51:35] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 10:51:37] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
Performing system checks...

System check identified no issues (0 silenced).
May 22, 2017 - 10:51:09
Django version 1.10.6, using settings 'attendancy.settings'
Starting development server at http://10.4.41.154:8000/
Quit the server with CONTROL-C.
fredy
2017-05-22
post assistencia
10:29
Assistencia object
fredy
2017-05-22
fredy
2017-05-22
Internal Server Error: /WEB/profe/assistenciaclasse/
Traceback (most recent call last):
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/alumne/Attendancy/WEB/views.py", line 486, in assistencia_classe
    a.entrada = assistenciaAlumne.entrada.isoformat()
NameError: global name 'assistenciaAlumne' is not defined
[22/May/2017 10:54:43] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 500 77570
Performing system checks...

System check identified no issues (0 silenced).
May 22, 2017 - 10:54:40
Django version 1.10.6, using settings 'attendancy.settings'
Starting development server at http://10.4.41.154:8000/
Quit the server with CONTROL-C.
fredy
2017-05-22
[22/May/2017 10:55:27] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4524
[22/May/2017 10:56:35] "PUT /API/classes/51/assistencia/04:1B:BA:4A:1F:C3/ HTTP/1.1" 400 41
[22/May/2017 10:56:40] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4524
[22/May/2017 10:56:43] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4524
[22/May/2017 10:56:44] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4524
[22/May/2017 10:56:46] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4524
[22/May/2017 11:00:03] "POST /API/classes/51/assistencia/04:1B:BA:4A:1F:C3/ HTTP/1.1" 201 0
[22/May/2017 11:04:10] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 11:04:13] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 11:04:47] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 11:04:49] "GET /WEB/profe/ HTTP/1.1" 200 3054
[22/May/2017 11:04:50] "GET /WEB/profe/assigsprofessor/ HTTP/1.1" 200 4063
[22/May/2017 11:04:52] "GET /WEB/profe/alumnesprofessor/?assignatura=PTI HTTP/1.1" 200 3679
[22/May/2017 11:04:53] "GET /WEB/profe/historialAlumne/?alumne=fredy&assignatura=PTI HTTP/1.1" 200 9095
[22/May/2017 11:04:56] "GET /WEB/profe/calendar/ HTTP/1.1" 200 5503
[22/May/2017 11:04:56] "GET /WEB/profe/json/?from=1493589600000&to=1496268000000 HTTP/1.1" 200 6257
[22/May/2017 11:04:56] "GET /static/tmpls/month.html?_=1495447441039 HTTP/1.1" 200 935
[22/May/2017 11:04:56] "GET /static/tmpls/month-day.html?_=1495447441056 HTTP/1.1" 200 625
[22/May/2017 11:04:56] "GET /static/tmpls/events-list.html?_=1495447441144 HTTP/1.1" 200 490
[22/May/2017 11:04:58] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 11:05:34] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 11:06:10] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 11:08:26] "GET /WEB/profe/ HTTP/1.1" 200 3054
[22/May/2017 11:08:37] "GET /WEB/profe/assigsprofessor/ HTTP/1.1" 200 4063
[22/May/2017 11:08:42] "GET /WEB/profe/classesassigprofessor/?assignatura=PTI HTTP/1.1" 200 3880
[22/May/2017 11:08:47] "GET /WEB/profe/calendar/ HTTP/1.1" 200 5503
[22/May/2017 11:08:48] "GET /WEB/profe/json/?from=1493589600000&to=1496268000000 HTTP/1.1" 200 6257
[22/May/2017 11:08:48] "GET /static/tmpls/month.html?_=1495447672824 HTTP/1.1" 200 935
[22/May/2017 11:08:48] "GET /static/tmpls/month-day.html?_=1495447672840 HTTP/1.1" 200 625
[22/May/2017 11:08:48] "GET /static/tmpls/events-list.html?_=1495447672917 HTTP/1.1" 200 490
[22/May/2017 11:08:54] "GET /WEB/profe/assigsprofessor/ HTTP/1.1" 200 4063
[22/May/2017 11:08:56] "GET /WEB/profe/alumnesprofessor/?assignatura=PTI HTTP/1.1" 200 3679
[22/May/2017 11:09:05] "GET /WEB/profe/historialAlumne/?alumne=fredy&assignatura=PTI HTTP/1.1" 200 9095
[22/May/2017 11:09:30] "GET /WEB/profe/calendar/ HTTP/1.1" 200 5503
[22/May/2017 11:09:31] "GET /WEB/profe/json/?from=1493589600000&to=1496268000000 HTTP/1.1" 200 6257
[22/May/2017 11:09:31] "GET /static/tmpls/month.html?_=1495447715743 HTTP/1.1" 200 935
[22/May/2017 11:09:31] "GET /static/tmpls/month-day.html?_=1495447715759 HTTP/1.1" 200 625
[22/May/2017 11:09:31] "GET /static/tmpls/events-list.html?_=1495447715842 HTTP/1.1" 200 490
[22/May/2017 11:09:38] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 11:09:49] "GET /static/tmpls/month.html?_=1495447734145 HTTP/1.1" 200 935
[22/May/2017 11:09:49] "GET /static/tmpls/month-day.html?_=1495447734222 HTTP/1.1" 200 625
[22/May/2017 11:09:49] "GET /static/tmpls/events-list.html?_=1495447734303 HTTP/1.1" 200 490
[22/May/2017 11:09:52] "GET /WEB/logout/ HTTP/1.1" 302 0
[22/May/2017 11:09:52] "GET /WEB/ HTTP/1.1" 200 1588
[22/May/2017 11:09:57] "POST /WEB/ HTTP/1.1" 302 0
[22/May/2017 11:09:57] "GET /WEB/ HTTP/1.1" 302 0
[22/May/2017 11:09:57] "GET /WEB/sysadmin/ HTTP/1.1" 200 3184
[22/May/2017 11:10:02] "GET /WEB/sysadmin/professors/ HTTP/1.1" 200 4247
[22/May/2017 11:10:11] "GET /WEB/sysadmin/alumnes/ HTTP/1.1" 200 4797
[22/May/2017 11:10:13] "GET /WEB/sysadmin/sales/ HTTP/1.1" 200 3665
[22/May/2017 11:10:14] "GET /WEB/sysadmin/assignatures/ HTTP/1.1" 200 4244
[22/May/2017 11:10:16] "GET /WEB/sysadmin/crearclasse/ HTTP/1.1" 200 23444
[22/May/2017 11:11:10] "POST /WEB/sysadmin/crearclasse/ HTTP/1.1" 302 0
[22/May/2017 11:11:10] "GET /WEB/sysadmin/assignatures HTTP/1.1" 301 0
[22/May/2017 11:11:10] "GET /WEB/sysadmin/assignatures/ HTTP/1.1" 200 4603
[22/May/2017 11:11:22] "GET /WEB/sysadmin/sales/ HTTP/1.1" 200 3665
[22/May/2017 11:11:29] "GET /WEB/sysadmin/assignatures/ HTTP/1.1" 200 4603
[22/May/2017 11:11:44] "GET /WEB/sysadmin/sales/ HTTP/1.1" 200 3665
[22/May/2017 11:11:53] "GET /WEB/logout/ HTTP/1.1" 302 0
[22/May/2017 11:11:53] "GET /WEB/ HTTP/1.1" 200 1588
[22/May/2017 11:11:56] "POST /WEB/ HTTP/1.1" 302 0
[22/May/2017 11:11:56] "GET /WEB/ HTTP/1.1" 302 0
[22/May/2017 11:11:56] "GET /WEB/profe/ HTTP/1.1" 200 3055
[22/May/2017 11:11:58] "GET /WEB/profe/assigsprofessor/ HTTP/1.1" 200 3688
[22/May/2017 11:12:01] "GET /WEB/profe/alumnesprofessor/?assignatura=TXC HTTP/1.1" 200 3357
[22/May/2017 11:12:03] "GET /WEB/profe/calendar/ HTTP/1.1" 200 5504
[22/May/2017 11:12:03] "GET /WEB/profe/json/?from=1493589600000&to=1496268000000 HTTP/1.1" 200 3072
[22/May/2017 11:12:04] "GET /static/tmpls/month.html?_=1495447868670 HTTP/1.1" 200 935
[22/May/2017 11:12:04] "GET /static/tmpls/month-day.html?_=1495447868689 HTTP/1.1" 200 625
[22/May/2017 11:12:04] "GET /static/tmpls/events-list.html?_=1495447868766 HTTP/1.1" 200 490
[22/May/2017 11:12:06] "GET /WEB/profe/ HTTP/1.1" 200 3055
[22/May/2017 11:12:10] "GET /WEB/logout/ HTTP/1.1" 302 0
[22/May/2017 11:12:10] "GET /WEB/ HTTP/1.1" 200 1588
[22/May/2017 11:12:13] "POST /WEB/ HTTP/1.1" 302 0
[22/May/2017 11:12:13] "GET /WEB/ HTTP/1.1" 302 0
[22/May/2017 11:12:13] "GET /WEB/profe/ HTTP/1.1" 200 3054
[22/May/2017 11:13:12] "GET /API/classes?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 301 0
[22/May/2017 11:13:12] "GET /API/classes/?mac=B8%3A27%3AEB%3AB4%3AE2%3A05 HTTP/1.1" 200 163
[22/May/2017 11:13:18] "GET /WEB/profe/calendar/ HTTP/1.1" 200 5503
[22/May/2017 11:13:18] "GET /WEB/profe/json/?from=1493589600000&to=1496268000000 HTTP/1.1" 200 6257
[22/May/2017 11:13:18] "GET /static/tmpls/month.html?_=1495447943170 HTTP/1.1" 200 935
[22/May/2017 11:13:18] "GET /static/tmpls/month-day.html?_=1495447943187 HTTP/1.1" 200 625
[22/May/2017 11:13:18] "GET /static/tmpls/events-list.html?_=1495447943265 HTTP/1.1" 200 490
[22/May/2017 11:13:20] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4256
[22/May/2017 11:13:43] "POST /API/classes/51/assistencia/04:1B:BA:4A:1F:C3/ HTTP/1.1" 201 0
[22/May/2017 11:14:02] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4321
[22/May/2017 11:15:39] "PUT /API/classes/51/assistencia/04:1B:BA:4A:1F:C3/ HTTP/1.1" 400 41
[22/May/2017 11:15:59] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4321
[22/May/2017 11:16:01] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4321
Performing system checks...

System check identified no issues (0 silenced).
May 22, 2017 - 10:55:25
Django version 1.10.6, using settings 'attendancy.settings'
Starting development server at http://10.4.41.154:8000/
Quit the server with CONTROL-C.
fredy
2017-05-22
fredy
2017-05-22
fredy
2017-05-22
fredy
2017-05-22
fredy
2017-05-22
post assistencia
10:38
Assistencia object
fredy
2017-05-22
fredy
2017-05-22
fredy
2017-05-22
fredy
2017-05-22
fredy
2017-05-22
fredy
2017-05-22
fredy
2017-05-22
B8:27:EB:B4:E2:05
fredy
2017-05-22
post assistencia
10:51
Assistencia object
fredy
2017-05-22
fredy
2017-05-22
fredy
2017-05-22
[22/May/2017 11:19:08] "POST /API/classes/51/assistencia/04:1B:BA:4A:1F:C3/ HTTP/1.1" 201 0
[22/May/2017 11:19:12] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4321
[22/May/2017 11:19:13] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4321
[22/May/2017 11:20:24] "PUT /API/classes/51/assistencia/04:1B:BA:4A:1F:C3/ HTTP/1.1" 204 0
[22/May/2017 11:20:32] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4327
[22/May/2017 11:20:39] "GET /WEB/profe/assigsprofessor/ HTTP/1.1" 200 4063
[22/May/2017 11:20:41] "GET /WEB/profe/alumnesprofessor/?assignatura=PTI HTTP/1.1" 200 3679
[22/May/2017 11:20:44] "GET /WEB/profe/historialAlumne/?alumne=fredy&assignatura=PTI HTTP/1.1" 200 9095
[22/May/2017 11:22:44] "GET /WEB/profe/calendar/ HTTP/1.1" 200 5503
[22/May/2017 11:22:45] "GET /WEB/profe/json/?from=1493589600000&to=1496268000000 HTTP/1.1" 200 6257
[22/May/2017 11:22:45] "GET /static/tmpls/month.html?_=1495448509719 HTTP/1.1" 200 935
[22/May/2017 11:22:45] "GET /static/tmpls/month-day.html?_=1495448509738 HTTP/1.1" 200 625
[22/May/2017 11:22:45] "GET /static/tmpls/events-list.html?_=1495448509817 HTTP/1.1" 200 490
[22/May/2017 11:22:49] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4327
[22/May/2017 11:26:32] "GET /API/alumnes/ HTTP/1.1" 405 5388
[22/May/2017 11:27:25] "POST /API/alumnes/ HTTP/1.1" 201 5301
[22/May/2017 11:27:34] "GET /WEB/logout/ HTTP/1.1" 302 0
[22/May/2017 11:27:34] "GET /WEB/ HTTP/1.1" 200 1588
[22/May/2017 11:27:42] "POST /WEB/ HTTP/1.1" 302 0
[22/May/2017 11:27:42] "GET /WEB/ HTTP/1.1" 302 0
[22/May/2017 11:27:42] "GET /WEB/sysadmin/ HTTP/1.1" 200 3184
[22/May/2017 11:27:49] "GET /WEB/sysadmin/alumnes/ HTTP/1.1" 200 5194
[22/May/2017 11:28:44] "GET /WEB/sysadmin/assignatures/ HTTP/1.1" 200 4603
[22/May/2017 11:29:07] "GET /API/assignatures/lXBS66Ngn6l0VfVLjrA7g8v26kou6sMB/alumnes/dani HTTP/1.1" 301 0
[22/May/2017 11:29:07] "GET /API/assignatures/lXBS66Ngn6l0VfVLjrA7g8v26kou6sMB/alumnes/dani/ HTTP/1.1" 405 5678
Internal Server Error: /API/assignatures/lXBS66Ngn6l0VfVLjrA7g8v26kou6sMB/alumnes/dani/
Traceback (most recent call last):
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 405, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
[22/May/2017 11:29:16] "POST /API/assignatures/lXBS66Ngn6l0VfVLjrA7g8v26kou6sMB/alumnes/dani/ HTTP/1.1" 500 16265
[22/May/2017 11:29:16] "GET /API/assignatures/lXBS66Ngn6l0VfVLjrA7g8v26kou6sMB/alumnes/dani/ HTTP/1.1" 405 5678
Internal Server Error: /API/assignatures/lXBS66Ngn6l0VfVLjrA7g8v26kou6sMB/alumnes/dani/
Traceback (most recent call last):
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 485, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/alumne/.virtualenvs/djangodev/local/lib/python2.7/site-packages/rest_framework/views.py", line 405, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<type 'NoneType'>`
[22/May/2017 11:29:23] "POST /API/assignatures/lXBS66Ngn6l0VfVLjrA7g8v26kou6sMB/alumnes/dani/ HTTP/1.1" 500 16265
[22/May/2017 11:29:23] "GET /API/assignatures/lXBS66Ngn6l0VfVLjrA7g8v26kou6sMB/alumnes/dani/ HTTP/1.1" 405 5678
[22/May/2017 11:29:44] "GET /WEB/logout/ HTTP/1.1" 302 0
[22/May/2017 11:29:44] "GET /WEB/ HTTP/1.1" 200 1588
[22/May/2017 11:29:47] "POST /WEB/ HTTP/1.1" 302 0
[22/May/2017 11:29:47] "GET /WEB/ HTTP/1.1" 302 0
[22/May/2017 11:29:47] "GET /WEB/profe/ HTTP/1.1" 200 3054
[22/May/2017 11:29:49] "GET /WEB/profe/assigsprofessor/ HTTP/1.1" 200 4063
[22/May/2017 11:29:51] "GET /WEB/profe/alumnesprofessor/?assignatura=PTI HTTP/1.1" 200 3991
[22/May/2017 11:29:59] "GET /WEB/profe/historialAlumne?alumne=dani&assignatura=PTI HTTP/1.1" 301 0
[22/May/2017 11:29:59] "GET /WEB/profe/historialAlumne/?alumne=dani&assignatura=PTI HTTP/1.1" 200 9095
[22/May/2017 11:30:02] "GET /WEB/profe/assigsprofessor/ HTTP/1.1" 200 4063
[22/May/2017 11:30:03] "GET /WEB/profe/calendar/ HTTP/1.1" 200 5503
[22/May/2017 11:30:04] "GET /WEB/profe/json/?from=1493589600000&to=1496268000000 HTTP/1.1" 200 6257
[22/May/2017 11:30:04] "GET /static/tmpls/month.html?_=1495448948788 HTTP/1.1" 200 935
[22/May/2017 11:30:04] "GET /static/tmpls/month-day.html?_=1495448948803 HTTP/1.1" 200 625
[22/May/2017 11:30:04] "GET /static/tmpls/events-list.html?_=1495448948879 HTTP/1.1" 200 490
[22/May/2017 11:30:05] "GET /WEB/profe/assistenciaclasse/?classe=51&data=2017-05-22%2010:00:00 HTTP/1.1" 200 4573
